services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=gamify_gym'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '5235:3306'
