services:
  mysql:
    container_name: GG-Database
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - '${DB_PORT}:3306'
  app:
  container_name: GG-Backend
  build:
    context: .
    dockerfile: dockerfile
  ports:
    - '${APP_PORT}:8080'
  depends_on:
    - mysql
